### PR TITLE
Reading tokens from file instructions typo fix

### LINKED ISSUE #15: Reading tokens from file instructions typo
The documentation states:

> This library also allows reading tokens directly from a file. The token needs to be in a file name ${CREDENTIALS_DIR}/${TOKEN_NAME}-secret:

However, this is incorrect as shown here: https://github.com/zalando-stups/python-tokens/blob/48f4dd8cff6260d7338c3063f79733ae77813784/tokens/__init__.py#L95

### PR DESCRIPTION
**Pull request by outime**
Fixes #15

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks!

**Comment by hjacobs** [comment]
👍

**Comment by jfuentescpp** [comment]
This PR saved me going to the code. Opened for 1 year ... 
Should be merged ?

**Review by mikkeloscar — APPROVED** [review]

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
